In [1]:
import numpy as np

In [2]:
print(np.arange(3)) 
print(np.arange(2, 5))
print(np.arange(1, 9, 2))

[0 1 2]
[2 3 4]
[1 3 5 7]


In [3]:
arr1 = np.random.randint(100, size=(5)) 
print(arr1, "\n")

arr2 = np.random.randint(100, size=(3, 5))
print(arr2, "\n")

arr3 = np.random.randint(100, size=(3, 5, 2))
print(arr3)

[60 46 42 98 52] 

[[86 14 18 91 58]
 [70 27 42 38 88]
 [44  1 37  3 46]] 

[[[ 7 14]
  [66 14]
  [ 0 44]
  [83 26]
  [83 26]]

 [[67 35]
  [29 24]
  [66 47]
  [81 71]
  [23 83]]

 [[70 49]
  [25 41]
  [65 72]
  [68 22]
  [47 35]]]


In [6]:
print("arr1.ndim = ", arr1.ndim)
print("arr2.ndim = ", arr2.shape)
print("arr2.size = ", arr2.size)

print("arr2.dtype = ", arr2.dtype)
print("arr2.itemsize = ", arr2.itemsize) 

arr4 = np.array([1.5, 2.3, 3.4])
print("arr4.itemsize = ", arr4.itemsize)

print("arr2.nbytes = ", arr2.nbytes)

arr1.ndim =  1
arr2.ndim =  (3, 5)
arr2.size =  15
arr2.dtype =  int32
arr2.itemsize =  4
arr4.itemsize =  8
arr2.nbytes =  60


In [7]:
np.random.seed(1)
arr = np.random.randint(10, size=(3, 4))
print(arr, "\n")

arr_sub = arr[:2, :2]
print(arr_sub, "\n")

arr_sub[0, 0] = -1
print(arr_sub, "\n")
print(arr)

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]] 

[[5 8]
 [0 0]] 

[[-1  8]
 [ 0  0]] 

[[-1  8  9  5]
 [ 0  0  1  7]
 [ 6  9  2  4]]


In [8]:
np.random.seed(1)
arr = np.random.randint(10, size=(3, 4))
print(arr, "\n")

arr_sub = arr[:2, :2].copy()
print(arr_sub, "\n")

arr_sub[0, 0] = -1
print(arr_sub, "\n")

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]] 

[[5 8]
 [0 0]] 

[[-1  8]
 [ 0  0]] 



In [9]:
arr = np.arange(1, 10)
print(arr, "\n")

grid = arr.reshape(3, 3)
print(grid)

[1 2 3 4 5 6 7 8 9] 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
arr = np.array([1, 2, 3])
print(arr)
print("arr.ndim = ", arr.ndim)
print("arr.shape = ", arr.shape)

print("\n")

arr_new = arr[:, np.newaxis]
print(arr_new)
print("arr_new.ndim = ", arr_new.ndim)
print("arr_new.shape = ", arr_new.shape)

[1 2 3]
arr.ndim =  1
arr.shape =  (3,)


[[1]
 [2]
 [3]]
arr_new.ndim =  2
arr_new.shape =  (3, 1)


In [11]:
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])
arr_3 = np.array([7, 8, 9])

arr_total = np.concatenate([arr_1, arr_2, arr_3])
print(arr_total)

arr_total = np.vstack([arr_1, arr_2, arr_3])
print(arr_total)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
arr = [1, 2, 3, 99, 99, 3, 2, 1]
print(arr)

arr_1, arr_2, arr3 = np.split(arr, [3, 5])
print(arr_1, arr_2, arr_3)

[1, 2, 3, 99, 99, 3, 2, 1]
[1 2 3] [99 99] [7 8 9]
